In [2]:
import pandas as pd
import random
import numpy as np

In [39]:
def initialize(p_zero, N):
    #create the map that we're trying to navigate. 
    #this is in form of adjacency matrix, randomly stimulated, how far intersections/nodes are from each other
    #nxn matrix, where each row and column correspond to an intersection on a map or a node
    #x_ij, then is equal to amount of time that it takes to get from position i to position j
    #practically, we need a matrix with some numeric values in it. 
    #for paths bw nodes i, j that do not exist, we'll assign 0 to them
    #i.e. if you can not go directly form i to j, then direct path or simply, 'path' does not exist

    #for initilisation, we need parameters
    #proportion of xeros in final matrix -> probability of zero, to control how sparse the map is -> p_zero

    themap = np.zeros((N,N))
    for i in range(0,N):
        for j in range(0, i): #'.' run the second loop only till i-1, since the adjecency matrix is symmetric
            
            if random.random()> p_zero:
                themap[i][j] = random.random() *100
                themap[j][i] = themap[i][j]
                #if the p_zero is less than some random value then only assign 0, we can control the sparcity of the matrix 
    return themap   

def create_starting_population(size, max_route_length, N):
    
    #this just creates a population of different routes of a fixed size, simple
    #it's gonna loop through the create_new_member function, to create a population with different starting routes
    population = []
    
    for i in range(0, size):
        population.append(create_new_member(max_route_length, N))

    return population


In [74]:
a = initialize(p_zero=0.1, N=5)
a

array([[ 0.        , 20.65395789, 71.41277614, 32.20885241, 62.39483921],
       [20.65395789,  0.        , 13.43063537, 79.95913131, 27.3161582 ],
       [71.41277614, 13.43063537,  0.        , 49.02138336, 93.71867008],
       [32.20885241, 79.95913131, 49.02138336,  0.        , 24.0590257 ],
       [62.39483921, 27.3161582 , 93.71867008, 24.0590257 ,  0.        ]])

In [ ]:
def fitness(member, themap):
    score = 0

    for i in range(1, member):
        score = score + themap[route[i-1]][route[i]] 
        #for the scores, we're just adding the value of distance in themap
        #yaha par there is no objective function, instead, scores seedha adjecancy matrix me hi hai

    return score

In [88]:
def crossover(a,b):
    """The Breeding Step"""

    #cut the a and b randomly
    cut_a = random.randint(1, len(a)-1) #1 to leng(a)-1 ke beech koi bhi number
    cut_b = random.randint(1, len(b)-1)

    new_a1 = a[0:cut_a] #first part of a
    new_b1 = b[0:cut_b] #first part of b

    new_a2 = a[cut_a:-1]
    new_b2 = b[cut_b:-1]

    new_a = np.append(new_a1, new_a2)
    new_b = np.append(new_b1, new_b2)

    print(cut_a, cut_b)
    print(new_a, new_b)



    #Upon the crossover is done, we gotta also check whether the resulting offprings, 
    #i.e. the resulting routes are valid routes or not.
    return (a,b)

In [ ]:
def mutate(route, probability): #member is nothing but a path
    for i in range(0, len(member)):
        if 

    return member

In [80]:
def create_new_member(themap):
    #here we create a new route
    #the new route can have any number of steps, sp we'll select that randomly
    #the structure of the route will be a vextor of integers where each value is the next step in the route
    #Everyone starts at 0, so the first value in thevector will indicate where to attempt to go next.
    #i.e., if v_i = 4, then that would correspond to X_0,4 in the map that was created at initialization

    #N is the size of the map, so we need to make sure that
    #we do not generate any values that exceed the size of the map

    #-------------------------
    # route_length = random.randint(0,max_route_length)

    # route = np.zeros(route_length)
    # print(route)
    # for i in range(0, route_length):
    #     route[i] = random.randint(0,N-1)
    #--------------------------

    #now, we need to be sure that the route is valid
    #to do that, we need to go thourgh a few steps,

    #Step1: get rid of all the values in the route that do not correspond to a non-zero value on themap
    #in other words, if we try to go from i to j, but it is not possible to go from i to j, then we need to 
    #get rid of that

    # print(route)
    # counter = 0
    # go = True

    # for i in range(0, len(route)):
    #     if themap[i][route[i]] == 0:
    # while go:
    #     #if the path doesnt exist
    #     print(counter)
    #     if themap[counter][route[counter]] == 0:
    #         #delete the point and go on to the next path
    #         np.delete(route, counter)
    #     else:
    #         #else move on
    #         counter+=1
        
    #     #if its the last point, then stop going
    #     if counter == len(route) - 1:
    #         go = False


    #Step2: we need to make sure that the route actually ends at the right place
    #In this case, the destination is point N-1 (the last point)
    #so we will simply add random values untill we connect to that final point
    #it's not the most efficient approach, but hopefully it will get us there

    N = len(themap)
    
    route = np.zeros(1, dtype=int)
    print(route)
    go = True
    
    i = 1
    
    while go:
        
        possible_values = np.nonzero(themap[route[i-1]])
        # print(i)
        # print(route[i-1])
        # print(themap[route[i-1]])
        proposed_value = random.randint(0,len(possible_values[0])-1)
        route = np.append(route, possible_values[0][proposed_value])
                
        if route[i] == N-1:
            go = False
        else:
            i += 1
    
    return route
   

In [85]:
create_new_member(a)

[0]
1
0
[ 0.         20.65395789 71.41277614 32.20885241 62.39483921]
2
3
[32.20885241 79.95913131 49.02138336  0.         24.0590257 ]
3
1
[20.65395789  0.         13.43063537 79.95913131 27.3161582 ]


array([0, 3, 1, 4], dtype=int64)

In [87]:
np.nonzero([ 0, 20.65395789, 71.41277614, 32.20885241, 62.39483921]
           )

(array([1, 2, 3, 4], dtype=int64),)